CREATE TABLE AR_ASSOCIATIONS (
  ID BIGSERIAL PRIMARY KEY,
  TARGET VARCHAR NOT NULL,
  RESPONSE VARCHAR NOT NULL
);

CREATE TABLE ORDERS (
  ID BIGSERIAL PRIMARY KEY,
  SHIP_DATE TIMESTAMP NULL,
  STATUS VARCHAR NOT NULL,
  COMPLETE BOOLEAN NOT NULL
);

CREATE TABLE USERS (
  ID BIGSERIAL PRIMARY KEY,
  USER_NAME VARCHAR NOT NULL UNIQUE,
  FIRST_NAME VARCHAR NOT NULL,
  LAST_NAME VARCHAR NOT NULL,
  EMAIL VARCHAR NOT NULL,
  PASSWORD VARCHAR NOT NULL,
  PHONE VARCHAR NOT NULL
);
